name: hashes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-hashes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: "recipe/i6_experiments"
    - uses: actions/checkout@v2
      with:
        repository: "rwth-i6/i6_core"
        path: "recipe/i6_core"
    - uses: actions/checkout@v2
      with:
        repository: "rwth-i6/sisyphus"
        path: "sisyphus"
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup Sisyphus environment
      run: |
        pip install --user --upgrade pip setuptools wheel
        cd sisyphus
        python3 setup.py install
        cd ..
        pip install flask
        pip install -r recipe/i6_core/requirements.txt
        ln -s recipe/i6_experiments/tests/hash_tests config
        ln -s recipe/i6_experiments/tests/check_jobs.py check_jobs.py
    - name: Test hashes
      run: |
        find config -name '*.py' -exec python check_jobs.py  {} \;



